# Start from the official Postgres image
FROM postgres:alpine

# Copy initialization scripts
COPY ./sql/databases.sql /docker-entrypoint-initdb.d/1.databases.sql
COPY ./AccountService/sql/schema.sql /docker-entrypoint-initdb.d/2.schema.sql
COPY ./AccountService/sql/data.sql /docker-entrypoint-initdb.d/3.data.sql
COPY ./ProductService/sql/schema.sql /docker-entrypoint-initdb.d/4.schema.sql
COPY ./ProductService/sql/data.sql /docker-entrypoint-initdb.d/5.data.sql
