name: We app Tests

on:
  push:
    branches: [ main ]

env:
  POSTGRES_DB: ${{ vars.POSTGRES_DB}}
  POSTGRES_USER: ${{ vars.POSTGRES_USER}}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
  ACCESS_TOKEN: ${{ secrets.MASTER_SECRET}}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4.1.3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run cis
      - run: npm run lints
      - run: npm run docker-up
      - name: Sleep for 20 seconds
        run: sleep 20s
      - name: Run All tests
        run: npm run tests  
        shell: bash
      - run: npm run docker-down
